### ISSUE TITLE
packaging dependency: optional or mandatory?

### ISSUE THREAD

**Issue by ffontaine** [thombashi/typepy#3]
packaging has been added as a mandatory dependency since version 1.1.3 and https://github.com/thombashi/typepy/commit/750b02e97d6e07ce4df2b6277b1d718ccc89f621. However, it is only used in `typepy/converter/_datetime.py` so I assume that packaging is not mandatory but optional and so could be moved from `requirements/requirements.txt` to `DATETIME_REQUIRES` in `setup.py`?

**Comment by thombashi** [comment]
Thank you for your report.

I had change the dependency to an optional at `typepy 1.1.5`.
